// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	proto/user.proto

It has these top-level messages:
	StatusResponse
	User
	CreateUserRequest
	GetUserByIdRequest
	GetUserByIdResponse
	DeleteUserRequest
	RegisterUserRequest
	LoginRequest
	LoginResponse
	Empty
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/any"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	// Member User
	RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...client.CallOption) (*StatusResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*StatusResponse, error)
	GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*GetUserByIdResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*StatusResponse, error)
}

type authClient struct {
	c           client.Client
	serviceName string
}

func NewAuthClient(serviceName string, c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &authClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authClient) RegisterUser(ctx context.Context, in *RegisterUserRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.RegisterUser", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...client.CallOption) (*LoginResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Login", in)
	out := new(LoginResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.CreateUser", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) GetUserById(ctx context.Context, in *GetUserByIdRequest, opts ...client.CallOption) (*GetUserByIdResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.GetUserById", in)
	out := new(GetUserByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.DeleteUser", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	// Member User
	RegisterUser(context.Context, *RegisterUserRequest, *StatusResponse) error
	Login(context.Context, *LoginRequest, *LoginResponse) error
	CreateUser(context.Context, *CreateUserRequest, *StatusResponse) error
	GetUserById(context.Context, *GetUserByIdRequest, *GetUserByIdResponse) error
	DeleteUser(context.Context, *DeleteUserRequest, *StatusResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) RegisterUser(ctx context.Context, in *RegisterUserRequest, out *StatusResponse) error {
	return h.AuthHandler.RegisterUser(ctx, in, out)
}

func (h *Auth) Login(ctx context.Context, in *LoginRequest, out *LoginResponse) error {
	return h.AuthHandler.Login(ctx, in, out)
}

func (h *Auth) CreateUser(ctx context.Context, in *CreateUserRequest, out *StatusResponse) error {
	return h.AuthHandler.CreateUser(ctx, in, out)
}

func (h *Auth) GetUserById(ctx context.Context, in *GetUserByIdRequest, out *GetUserByIdResponse) error {
	return h.AuthHandler.GetUserById(ctx, in, out)
}

func (h *Auth) DeleteUser(ctx context.Context, in *DeleteUserRequest, out *StatusResponse) error {
	return h.AuthHandler.DeleteUser(ctx, in, out)
}
