// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	StatusResponse
	User
	CreateUserRequest
	LoginRequest
	LoginResponse
	Empty
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Kết quả trả về
type StatusResponse struct {
	// Mã trạng thái trả về
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// Thông báo lỗi chung
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StatusResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *StatusResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type User struct {
	// Mã User (chuỗi ngẫu nhiên duy nhất)
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// Tên User
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// Họ User
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// Địa chỉ email, dùng luôn làm tài khoản đăng nhập
	Email string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	// Mật khẩu phải có tối thiểu 6 ký tự
	Password string `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	// Salt dùng để mã hóa password
	Salt string `protobuf:"bytes,6,opt,name=salt" json:"salt,omitempty"`
	// Số điện thoại
	Phone string `protobuf:"bytes,7,opt,name=phone" json:"phone,omitempty"`
	// Ảnh đại diện
	Avatar string `protobuf:"bytes,8,opt,name=avatar" json:"avatar,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *User) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type CreateUserRequest struct {
	// Tạo đối tượng User
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest struct {
	// Email
	Email string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	// Mật khẩu
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	// Ghi nhớ đăng nhập
	Remember bool `protobuf:"varint,3,opt,name=remember" json:"remember,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetRemember() bool {
	if m != nil {
		return m.Remember
	}
	return false
}

type LoginResponse struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*LoginRequest)(nil), "LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x6d, 0xf2, 0x25, 0x6d, 0x32, 0xfd, 0xda, 0x8f, 0x6f, 0x10, 0x59, 0x23, 0x42, 0xd9, 0x53,
	0x4f, 0x39, 0xb4, 0x77, 0x41, 0xc4, 0x9b, 0x78, 0x88, 0x78, 0x13, 0x64, 0xdb, 0x8c, 0x35, 0x90,
	0x64, 0xe3, 0xee, 0xb6, 0xe2, 0x1f, 0xf4, 0x77, 0x49, 0xa6, 0x4d, 0xb5, 0x8a, 0x07, 0x6f, 0xfb,
	0xde, 0xcb, 0xbc, 0xbc, 0x79, 0xbb, 0x00, 0x6b, 0x4b, 0x26, 0x6d, 0x8c, 0x76, 0x5a, 0x9e, 0xc3,
	0xf8, 0xd6, 0x29, 0xb7, 0xb6, 0x19, 0xd9, 0x46, 0xd7, 0x96, 0x10, 0x21, 0x58, 0xea, 0x9c, 0x84,
	0x37, 0xf1, 0xa6, 0x61, 0xc6, 0x67, 0x14, 0x30, 0xa8, 0xc8, 0x5a, 0xb5, 0x22, 0xe1, 0x4f, 0xbc,
	0x69, 0x9c, 0x75, 0x50, 0xbe, 0x79, 0x10, 0xdc, 0x59, 0x32, 0x38, 0x06, 0xbf, 0xc8, 0x79, 0x28,
	0xce, 0xfc, 0x22, 0xc7, 0x33, 0x80, 0xc7, 0xc2, 0x58, 0xf7, 0x50, 0xab, 0xaa, 0x9b, 0x8a, 0x99,
	0xb9, 0x51, 0x15, 0xe1, 0x29, 0xc4, 0xa5, 0xea, 0xd4, 0x3f, 0xac, 0x46, 0x2d, 0xc1, 0xe2, 0x11,
	0x84, 0x54, 0xa9, 0xa2, 0x14, 0x01, 0x0b, 0x5b, 0x80, 0x09, 0x44, 0x8d, 0xb2, 0xf6, 0x45, 0x9b,
	0x5c, 0x84, 0xdb, 0x89, 0x0e, 0xb7, 0xa1, 0xad, 0x2a, 0x9d, 0xe8, 0x33, 0xcf, 0xe7, 0xd6, 0xa5,
	0x79, 0xd2, 0x35, 0x89, 0xc1, 0xd6, 0x85, 0x01, 0x1e, 0x43, 0x5f, 0x6d, 0x94, 0x53, 0x46, 0x44,
	0x4c, 0xef, 0x90, 0x4c, 0xe1, 0xff, 0xa5, 0x21, 0xe5, 0xa8, 0xdd, 0x26, 0xa3, 0xe7, 0x35, 0x59,
	0x87, 0x27, 0x10, 0xb4, 0x5d, 0xf1, 0x5a, 0xc3, 0x59, 0x98, 0xb2, 0xc6, 0x94, 0xbc, 0x87, 0xbf,
	0xd7, 0x7a, 0x55, 0xd4, 0xdd, 0xa7, 0xfb, 0xcc, 0xde, 0x4f, 0x99, 0xfd, 0x2f, 0x99, 0x13, 0x88,
	0x0c, 0x55, 0x54, 0x2d, 0xc8, 0x70, 0x03, 0x51, 0xb6, 0xc7, 0xf2, 0x02, 0x46, 0x3b, 0xf7, 0xdd,
	0xad, 0xfc, 0xda, 0x5e, 0x0e, 0x20, 0xbc, 0xaa, 0x1a, 0xf7, 0x3a, 0x2b, 0x61, 0xd8, 0xe6, 0xb6,
	0x64, 0x36, 0xc5, 0x92, 0x70, 0x0a, 0x21, 0x5b, 0xe3, 0x28, 0xfd, 0xbc, 0x40, 0x32, 0x4e, 0x0f,
	0xfe, 0x28, 0x7b, 0x38, 0x07, 0xf8, 0xa8, 0x04, 0x31, 0xfd, 0xd6, 0x4f, 0xf2, 0x2f, 0x3d, 0x7c,
	0x3c, 0xb2, 0xb7, 0xe8, 0xf3, 0xbb, 0x9a, 0xbf, 0x07, 0x00, 0x00, 0xff, 0xff, 0x36, 0xb6, 0x2d,
	0x8b, 0x65, 0x02, 0x00, 0x00,
}
